'use client';
import { FormEvent, useState } from 'react';

type Row = Record<string, any>;
type Props = { data: Row; save: (name:string,payload:Row)=>Promise<any> };
const tabs=[['general','Thông tin chung'],['departments','Danh mục khoa'],['linen','Đồ vải'],['supply','Vật tư'],['packages','Gói cấp phát'],['staff','Nhân viên'],['password','Mật khẩu']];

export default function SettingsPanel({data,save}:Props){
 const [tab,setTab]=useState('general'); const [packageId,setPackageId]=useState(''); const [logo,setLogo]=useState(String(data.settings.find((x:Row)=>x.key==='LOGO_URL')?.value||''));
 const currentPackage=data.packages.find((x:Row)=>x.id===packageId);
 async function general(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await save('saveSettings',{rows:data.settings.map((x:Row)=>({key:x.key,value:x.key==='LOGO_URL'?logo:f.get(x.key),description:x.description}))})}
 async function chooseLogo(file?:File){if(!file)return;if(!/^image\/(png|jpeg)$/.test(file.type))throw new Error('Chỉ nhận ảnh PNG hoặc JPG.');const src=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(new Error('Không đọc được ảnh logo.'));reader.readAsDataURL(file)});const img=new Image();img.src=src;await new Promise<void>((resolve,reject)=>{img.onload=()=>resolve();img.onerror=()=>reject(new Error('Ảnh logo không hợp lệ.'))});const max=320,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Không xử lý được ảnh.');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);const result=canvas.toDataURL('image/jpeg',.82);if(result.length>500000)throw new Error('Ảnh logo quá lớn.');setLogo(result)}
 async function department(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await save('saveDepartment',{department:{code:String(f.get('code')).trim().toUpperCase(),name:String(f.get('name')).trim(),sort_order:Number(f.get('sort_order')),active:true}});e.currentTarget.reset()}
 async function catalog(e:FormEvent<HTMLFormElement>,type:'LINEN'|'SUPPLY'){e.preventDefault();const f=new FormData(e.currentTarget);await save('saveCatalog',{item:{code:String(f.get('code')).trim().toUpperCase(),name:String(f.get('name')).trim(),item_type:type,item_group:String(f.get('item_group')||'').trim(),unit:String(f.get('unit')||'cái').trim(),default_qty:Math.max(0,Number(f.get('default_qty'))),collectable:type==='LINEN'&&f.get('collectable')==='on',issuable:true,active:true,sort_order:Number(f.get('sort_order')||999)}});e.currentTarget.reset()}
 async function packageForm(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await save('savePackage',{package:{code:String(f.get('code')).trim().toUpperCase(),name:String(f.get('name')).trim(),sort_order:Number(f.get('sort_order')||999),active:true}});e.currentTarget.reset()}
 async function staffForm(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await save('saveStaff',{staff:{code:String(f.get('code')).trim().toUpperCase(),full_name:String(f.get('full_name')).trim(),department:String(f.get('department')||'').trim(),role:String(f.get('role')||'NHAN_VIEN'),active:true}});e.currentTarget.reset()}
 async function password(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await save('changePassword',{password:f.get('password')});e.currentTarget.reset()}
 const toggle=(kind:string,row:Row)=>save(kind,kind==='saveDepartment'?{department:{...row,active:!row.active}}:kind==='saveStaff'?{staff:{...row,active:!row.active}}:kind==='savePackage'?{package:{...row,active:!row.active}}:{item:{...row,active:!row.active}});
 const editDepartment=async(x:Row)=>{const name=window.prompt('Tên khoa',x.name);if(name===null)return;const order=window.prompt('Thứ tự',String(x.sort_order));if(order===null)return;await save('saveDepartment',{department:{...x,name:name.trim(),sort_order:Number(order)}})}
 const editCatalog=async(x:Row)=>{const name=window.prompt('Tên mặt hàng',x.name);if(name===null)return;const group=window.prompt('Nhóm',x.item_group||'');if(group===null)return;const qty=window.prompt('Số lượng mặc định',String(x.default_qty));if(qty===null)return;const unit=window.prompt('Đơn vị tính',x.unit);if(unit===null)return;await save('saveCatalog',{item:{...x,name:name.trim(),item_group:group.trim(),default_qty:Math.max(0,Number(qty)),unit:unit.trim()}})}
 const editPackage=async(x:Row)=>{const name=window.prompt('Tên gói cấp phát',x.name);if(name===null)return;await save('savePackage',{package:{...x,name:name.trim()}})}
 const editStaff=async(x:Row)=>{const name=window.prompt('Họ tên nhân viên',x.full_name);if(name===null)return;const department=window.prompt('Bộ phận',x.department||'');if(department===null)return;await save('saveStaff',{staff:{...x,full_name:name.trim(),department:department.trim()}})}
 async function packageItems(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!packageId)return;const f=new FormData(e.currentTarget);const items=data.items.map((x:Row)=>({itemId:x.id,active:f.get('show_'+x.id)==='on',quantity:Math.max(0,Number(f.get('qty_'+x.id)||0))}));await save('savePackageItems',{packageId,items})}
 const CatalogTable=({type}:{type:'LINEN'|'SUPPLY'})=>{const rows=data.items.filter((x:Row)=>x.item_type===type);return <><form className="card" onSubmit={e=>catalog(e,type)}><h2>Thêm {type==='LINEN'?'đồ vải':'vật tư'}</h2><div className="form-grid"><label>Mã<input name="code" required/></label><label>Tên<input name="name" required/></label><label>Nhóm<input name="item_group" defaultValue={type==='SUPPLY'?'VAT_TU':''}/></label><label>SL mặc định<input name="default_qty" type="number" min="0" defaultValue="1"/></label><label>Đơn vị<input name="unit" defaultValue="cái"/></label><label>Thứ tự<input name="sort_order" type="number" defaultValue="999"/></label>{type==='LINEN'&&<label><input name="collectable" type="checkbox" defaultChecked style={{width:'auto'}}/> Thu gom khi ra viện</label>}</div><div className="actions"><button className="btn success">＋ Thêm mới</button></div></form><Table headers={['Mã','Tên','Nhóm','SL mặc định','ĐVT','Trạng thái','Thao tác']} rows={rows.map((x:Row)=>[x.code,x.name,x.item_group,x.default_qty,x.unit,<Status key="s" active={x.active}/>,<span key="a"><button className="btn secondary" onClick={()=>editCatalog(x)}>Sửa</button> <button className={'btn '+(x.active?'danger':'success')} onClick={()=>toggle('saveCatalog',x)}>{x.active?'Ẩn':'Bật'}</button></span>])}/></>};
 return <section><div className="topbar"><div><h2>CÀI ĐẶT HỆ THỐNG</h2><span className="muted">Sửa tên bệnh viện, khoa, đồ vải, vật tư, gói cấp phát, nhân viên và mật khẩu.</span></div><span className="badge red">🔒 Chỉ người quản lý</span></div><div className="actions" style={{justifyContent:'flex-start'}}>{tabs.map(x=><button key={x[0]} className={'btn '+(tab===x[0]?'primary':'secondary')} onClick={()=>setTab(x[0])}>{x[1]}</button>)}</div>
 {tab==='general'&&<form className="card" onSubmit={general}><h2>Thông tin chung</h2>{data.settings.filter((x:Row)=>x.key!=='LOGO_URL').map((x:Row)=><label key={x.key}>{x.description}<input name={x.key} defaultValue={x.value}/></label>)}<label>Logo bệnh viện (PNG/JPG)<input type="file" accept="image/png,image/jpeg" onChange={e=>chooseLogo(e.target.files?.[0])}/></label>{logo&&<div style={{marginTop:10}}><div style={{width:148,height:148,border:'1px solid #d7deec',borderRadius:12,display:'grid',placeItems:'center',background:'#fff'}}><img src={logo} alt="Logo bệnh viện" style={{maxWidth:138,maxHeight:138,objectFit:'contain'}}/></div><button type="button" className="btn secondary" style={{marginTop:6}} onClick={()=>setLogo('')}>Xóa logo</button></div>}<div className="actions"><button className="btn success">Lưu thông tin</button></div></form>}
 {tab==='departments'&&<><form className="card" onSubmit={department}><h2>Thêm khoa</h2><div className="form-grid"><label>Mã<input name="code" required/></label><label>Tên khoa<input name="name" required/></label><label>Thứ tự<input name="sort_order" type="number" defaultValue="999"/></label></div><div className="actions"><button className="btn success">＋ Thêm khoa</button></div></form><Table headers={['Mã','Tên khoa','Thứ tự','Trạng thái','Thao tác']} rows={data.departments.map((x:Row)=>[x.code,x.name,x.sort_order,<Status key="s" active={x.active}/>,<span key="a"><button className="btn secondary" onClick={()=>editDepartment(x)}>Sửa</button> <button className={'btn '+(x.active?'danger':'success')} onClick={()=>toggle('saveDepartment',x)}>{x.active?'Ẩn':'Bật'}</button></span>])}/></>}
 {tab==='linen'&&<CatalogTable type="LINEN"/>}{tab==='supply'&&<CatalogTable type="SUPPLY"/>}
 {tab==='packages'&&<><form className="card" onSubmit={packageForm}><h2>Thêm gói cấp phát</h2><div className="form-grid"><label>Mã gói<input name="code" required/></label><label>Tên gói<input name="name" required/></label><label>Thứ tự<input name="sort_order" type="number" defaultValue="999"/></label></div><div className="actions"><button className="btn success">＋ Thêm gói</button></div></form><Table headers={['Mã','Tên gói','Thứ tự','Trạng thái','Thao tác']} rows={data.packages.map((x:Row)=>[x.code,x.name,x.sort_order,<Status key="s" active={x.active}/>,<span key="a"><button className="btn secondary" onClick={()=>editPackage(x)}>Đổi tên</button> <button className="btn primary" onClick={()=>setPackageId(x.id)}>Sửa nội dung</button> <button className={'btn '+(x.active?'danger':'success')} onClick={()=>toggle('savePackage',x)}>{x.active?'Ẩn':'Bật'}</button></span>])}/>{currentPackage&&<div style={{position:'fixed',inset:0,background:'rgba(20,28,55,.55)',zIndex:1000,display:'grid',placeItems:'center',padding:20}}><form className="card" style={{width:'min(760px,96vw)',maxHeight:'88vh',overflow:'auto'}} onSubmit={packageItems}><h2>Nội dung gói: {currentPackage.name}</h2><div className="table-wrap"><table><thead><tr><th>Nhóm</th><th>Mã</th><th>Tên mặt hàng</th><th>ĐVT</th><th>Hiện trong gói</th><th>Số lượng</th></tr></thead><tbody>{data.items.map((x:Row)=>{const old=data.packageItems.find((p:Row)=>p.package_id===packageId&&p.item_id===x.id);return <tr key={x.id}><td>{x.item_type==='LINEN'?'Đồ vải':'Vật tư'}</td><td>{x.code}</td><td>{x.name}</td><td>{x.unit}</td><td><input style={{width:'auto'}} name={'show_'+x.id} type="checkbox" defaultChecked={Boolean(old?.active)}/></td><td><input name={'qty_'+x.id} type="number" min="0" defaultValue={old?.quantity||0}/></td></tr>})}</tbody></table></div><div className="actions"><button type="button" className="btn secondary" onClick={()=>setPackageId('')}>Hủy</button><button className="btn success">Lưu nội dung gói</button></div></form></div>}</>}
 {tab==='staff'&&<><form className="card" onSubmit={staffForm}><h2>Thêm nhân viên</h2><div className="form-grid"><label>Mã NV<input name="code" required/></label><label>Họ tên<input name="full_name" required/></label><label>Bộ phận<input name="department"/></label><label>Vai trò<select name="role"><option value="NHAN_VIEN">Nhân viên</option><option value="QUAN_LY">Quản lý</option></select></label></div><div className="actions"><button className="btn success">＋ Thêm nhân viên</button></div></form><Table headers={['Mã','Họ tên','Bộ phận','Vai trò','Trạng thái','Thao tác']} rows={data.staff.map((x:Row)=>[x.code,x.full_name,x.department,x.role,<Status key="s" active={x.active}/>,<span key="a"><button className="btn secondary" onClick={()=>editStaff(x)}>Sửa</button> <button className={'btn '+(x.active?'danger':'success')} onClick={()=>toggle('saveStaff',x)}>{x.active?'Ẩn':'Bật'}</button></span>])}/></>}
 {tab==='password'&&<form className="card" onSubmit={password}><h2>Đổi mật khẩu quản lý</h2><label>Mật khẩu mới<input name="password" type="password" minLength={8} required/></label><div className="actions"><button className="btn warning">Đổi mật khẩu</button></div></form>}</section>
}
function Status({active}:{active:boolean}){return <span className={'badge '+(active?'green':'')}>{active?'Đang dùng':'Tạm ẩn'}</span>}
function Table({headers,rows}:{headers:string[],rows:any[][]}){return <div className="card section-gap"><div className="table-wrap"><table><thead><tr>{headers.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((x,j)=><td key={j}>{x}</td>)}</tr>)}</tbody></table></div></div>}

